name: hajjhealth
description: "An Apps to make medical solution for Hajj Users"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  firebase_core: ^3.13.0
  firebase_vertexai: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  firebase_database: ^11.3.5
  get: ^4.7.2
  google_fonts: ^6.2.1
  build_runner: ^2.4.15
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5
  json_serializable: ^6.9.5
  custom_lint: ^0.7.5

flutter:
  #fonts:
  # - family: Poppins
  #   fonts:
  #     - asset: fonts/Poppins-Regular.ttf
  #       weight: 400
  #     - asset: fonts/Poppins-Medium.ttf
  #       weight: 500
  #     - asset: fonts/Poppins-Bold.ttf
  #       weight: 700
  #     - asset: fonts/Poppins-Light.ttf
  #       weight: 300

  uses-material-design: true
  assets:
    - assets/img/nurse.png
    - assets/img/logo.png
    - prompt/system_prompt.md
